server:
  port: 8010
file:
#  path: /var/jenkins_home/workspace/ToolTool/src/main/resources/static/files
  path: /user.dir/src/main/resources/static/files
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.1:3306/tooltool?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: sbblocal
    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    smtp:
      host: smtp.gmail.com
      port: 587
      username: changgyu549@gmail.com
      password: pzgbscuypjrnondt
      auth: true
      starttls:
        enable: true
    subject:
      member:
        registration: Thank you for joining our site!