server:
  port: 8010
custom:
  genFileDirPath: /tooltool_gen
  resourcePath: file:///tooltool_gen/
  requestPath: /tooltool_gen/**
  originPath: /tooltool_gen/
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.17.0.1:3306/tooltool?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: sbblocal
    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
