server:
  port: 7070
spring:
  profiles:
    active:
    include: secret
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/tooltool?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    username: root
    password: gkdlfn12
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    subject:
      member:
        registration: Thank you for joining our site!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
custom:
  genFileDirPath: /Users/parkchang-gyu/Desktop/img_upload
  resourcePath: file:///Users/parkchang-gyu/Desktop/img_upload/
  requestPath: /img_upload/**
  originPath: /img_upload/
  site:
    name: ToolTool
    baseUrl: "http://tooltool.devp.kr:8010"
